services:
  freelance-app:
    build: .
    ports:
      - "10000:10000"
    volumes:
      # Монтируем папку uploads для сохранения файлов
      - ./app/uploads:/app/uploads
      # Временно отключено для пересоздания базы с FOREIGN KEY
      # - ./freelance.db:/app/freelance.db
    environment:
      - PORT=10000
    restart: unless-stopped
